# Generated by Django 6.0.4 on 2026-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_author_savednews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_published',
        ),
        migrations.AddField(
            model_name='news',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
